### ISSUE TITLE
Suggestion: Use x-instana-l for sampling

### ISSUE THREAD

**Issue by PSanetra** [instana/golang-sensor#30]
Hi,

in propagation.go `SpanContext.Sampled` is always set to false. There is still a todo _add configurable sampling strategy_.
https://github.com/instana/golang-sensor/blob/dd3b6b166b5c5a4527ea0317bc470c36e22054ca/propagation.go#L145

I asked myself why you don't inject "1" as trace level if `SpanContext.Sampled` is true and "0" if it is false.
https://github.com/instana/golang-sensor/blob/dd3b6b166b5c5a4527ea0317bc470c36e22054ca/propagation.go#L78

Then you could extract the level and use it to determine if you should set `SpanContext.Sampled` to true or false.

I think this behavior is backed by the instana documentation: 
_x-instana-l carries information about the trace level, where 0 means that no trace shall be recorded._
https://instana.atlassian.net/wiki/display/DOCS/Instana+Trace+Model

PSanetra

**Comment by pglombardo** [comment]
Hi @PSanetra - Since Instana is _trace everything/always_, these two fields have no current use.  e.g. we never sample and as a result don't use the `level` field.

We set these Keys/Headers to stay compliant and interoperable with OpenTracing but no action is ever taken by Instana based on the values of these fields.  This is definitely true for today and the short-term future but that may change eventually.

If this ever changes, we'll definitely do as you propose - just with the current way things are done, it doesn't make any sense.

I'll close this issue out but if I missed something or you feel there is still an issue, feel free to re-open.
